# # Use an official PHP image as a base image
# FROM php:8.2-fpm

# # Install the mysqli extension
# RUN docker-php-ext-install mysqli

# # Install MySQL client
# #RUN apt-get update && apt-get install -y mysql-client

# # Install other necessary tools if needed

# # Set up a working directory (you can customize this)
# WORKDIR /workspaces/php-mysql-container

# # Expose port 80 for web server if needed
# EXPOSE 8000

